name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # everyday at 3 am
  schedule:
    - cron:  '0 3 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      id: login
      run: docker login -u bharamicrosystems -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      id: build
      run: curl http://mirrors.jenkins.io/war-stable/|grep td|awk '{print $5}'|awk -F'"' '{print $2}'|awk -F'/' '{print $1}'| grep -v -e '^[[:space:]]*$'|  grep -v ".html"| tail -18| while read version; do docker build --build-arg version=$version . --file Dockerfile --tag bharamicrosystems/jenkins-distroless:$version; done
    - name: Push the Docker image
      id: push
      run: docker push bharamicrosystems/jenkins-distroless
